<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use DB;
use App\Models\Docente;
use Carbon\Carbon;

class DocentesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	$now = Carbon::now()->toDateTimeString();
		$docentes = array(
			array(
				"cedula" => 4977281,
				"nombres" => "LUIS ANTONIO",
				"apellidos" => "PASARELLA GUEVARA ",
				"nacionalidad" => "V",
				"fechan" => "1958-01-06",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 5013386,
				"nombres" => "PEDRO ELIAS",
				"apellidos" => "CARPIO ",
				"nacionalidad" => "V",
				"fechan" => "1952-06-29",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 8520453,
				"nombres" => "AMARILIS",
				"apellidos" => "ROMERO",
				"nacionalidad" => "V",
				"fechan" => "1958-06-17",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 8868268,
				"nombres" => "ALEXIS ALEJANDRO",
				"apellidos" => "ROGERS TONGIANI",
				"nacionalidad" => "V",
				"fechan" => "1962-11-18",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 8875814,
				"nombres" => "JOSÉ GABRIEL",
				"apellidos" => "MACHADO PEÑA",
				"nacionalidad" => "V",
				"fechan" => "1964-03-19",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 8879754,
				"nombres" => "CLAUDIA COROMOTO",
				"apellidos" => "IZARRA ",
				"nacionalidad" => "V",
				"fechan" => "1963-11-18",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 8882246,
				"nombres" => "LUIS FRANCISCO",
				"apellidos" => "AMUNDARAY ESPINOZA",
				"nacionalidad" => "V",
				"fechan" => "1966-01-14",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 8888081,
				"nombres" => "ARTURO JESUS",
				"apellidos" => "BETANCOURT MARTINEZ",
				"nacionalidad" => "V",
				"fechan" => "1965-12-16",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 8905923,
				"nombres" => "JAIME JOSE",
				"apellidos" => "GUTIERREZ RUIZ ",
				"nacionalidad" => "V",
				"fechan" => "1963-05-09",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 8956056,
				"nombres" => "NIRVIA DEL VALLE",
				"apellidos" => "RODRIGUEZ SALAZAR ",
				"nacionalidad" => "V",
				"fechan" => "1966-11-03",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 8957440,
				"nombres" => "BERKIS ZURILMA",
				"apellidos" => "CHINCHILLA ESPINOZA",
				"nacionalidad" => "V",
				"fechan" => "1966-11-28",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 10042405,
				"nombres" => "PEDRO LUIS",
				"apellidos" => "ROSAL ARIAS ",
				"nacionalidad" => "V",
				"fechan" => "1970-08-03",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 10928446,
				"nombres" => "RICHARD BUENA ",
				"apellidos" => "VENTURA GIL",
				"nacionalidad" => "V",
				"fechan" => "1977-08-04",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 11729328,
				"nombres" => "LUIS MANUEL",
				"apellidos" => "FLORES PARRA",
				"nacionalidad" => "V",
				"fechan" => "1974-10-04",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 12185193,
				"nombres" => "NORELIS SOLVEY",
				"apellidos" => "GARCIA BETANCOURT ",
				"nacionalidad" => "V",
				"fechan" => "1974-08-27",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 12598686,
				"nombres" => "MIGZORYS JOSEFINA",
				"apellidos" => "FERNÁNDEZ ORDAZ",
				"nacionalidad" => "V",
				"fechan" => "1976-09-01",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 12602020,
				"nombres" => "YUSMERIS DEL CARMEN",
				"apellidos" => "GARCIA SALAZAR",
				"nacionalidad" => "V",
				"fechan" => "2021-03-14",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 13313617,
				"nombres" => "YACIRIS DEL CARMEN",
				"apellidos" => "DAVILA TORRES ",
				"nacionalidad" => "V",
				"fechan" => "1978-01-08",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 13920745,
				"nombres" => "CAROLINA MABEL",
				"apellidos" => "CORDERO UREOLA ",
				"nacionalidad" => "V",
				"fechan" => "1979-02-09",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 14590972,
				"nombres" => "DICKSONBER ALBERTO",
				"apellidos" => "RODRÍGUEZ CRESPO",
				"nacionalidad" => "V",
				"fechan" => "1980-03-22",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 14883745,
				"nombres" => "VITRYS MILAGROS",
				"apellidos" => "MAITA ",
				"nacionalidad" => "V",
				"fechan" => "1980-03-21",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 15468137,
				"nombres" => "GUILLERMO JOSÉ",
				"apellidos" => "PRICE MALPICA ",
				"nacionalidad" => "V",
				"fechan" => "1983-02-25",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 15970323,
				"nombres" => "MARIA JOSÉ",
				"apellidos" => "ARENAS ESPAÑA",
				"nacionalidad" => "V",
				"fechan" => "1984-04-18",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 16432078,
				"nombres" => "OSCAR JOAQUIN",
				"apellidos" => "MARENCO CUELLO ",
				"nacionalidad" => "V",
				"fechan" => "1961-05-01",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 19382729,
				"nombres" => "SAMUEL SADRAC",
				"apellidos" => "BRAVO TORREALBA",
				"nacionalidad" => "V",
				"fechan" => "1991-06-05",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 19872686,
				"nombres" => "RAY JOSE",
				"apellidos" => "ALFONZO GUEVARA ",
				"nacionalidad" => "V",
				"fechan" => "1990-02-02",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 26355485,
				"nombres" => "JOSE RAFAEL",
				"apellidos" => "LOPEZ GUEVARA",
				"nacionalidad" => "V",
				"fechan" => "1998-07-08",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 3656752,
				"nombres" => "JOSÉ NOEL",
				"apellidos" => "VELASQUEZ AGUANES",
				"nacionalidad" => "V",
				"fechan" => "1953-03-16",
				"sexo" => "MASCULINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 5335393,
				"nombres" => "LUIS BELTRAN",
				"apellidos" => "QUIÑONEZ GONZALEZ",
				"nacionalidad" => "V",
				"fechan" => "1960-02-20",
				"sexo" => "MASCULINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 15469058,
				"nombres" => "JOSE LUIS",
				"apellidos" => "CARIAS GUEVARA",
				"nacionalidad" => "V",
				"fechan" => "1981-07-31",
				"sexo" => "MASCULINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 15347764,
				"nombres" => "HAYDEE CAROLINA",
				"apellidos" => "VALDEZ RAMOS",
				"nacionalidad" => "V",
				"fechan" => "1981-03-09",
				"sexo" => "FEMENINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 15457382,
				"nombres" => "NATHALIA PATRICIA",
				"apellidos" => "BRINES GURISMA",
				"nacionalidad" => "V",
				"fechan" => "1980-10-31",
				"sexo" => "FEMENINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 15251476,
				"nombres" => "DOUGLAS ANGEL",
				"apellidos" => "GUARNIZO BARRIOS",
				"nacionalidad" => "V",
				"fechan" => "1980-12-04",
				"sexo" => "MASCULINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 14975484,
				"nombres" => "WUILMER BENEDICTO",
				"apellidos" => "COLMENARES MALDONADO",
				"nacionalidad" => "V",
				"fechan" => "1982-11-23",
				"sexo" => "MASCULINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 14410768,
				"nombres" => "HAIBEE DE LUZ",
				"apellidos" => "REBOLLEDO TORRES",
				"nacionalidad" => "V",
				"fechan" => "1980-04-12",
				"sexo" => "FEMENINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 12194045,
				"nombres" => "DANIEL JOSE",
				"apellidos" => "BAES ARRECHEDERA",
				"nacionalidad" => "V",
				"fechan" => "1975-11-21",
				"sexo" => "MASCULINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 11724630,
				"nombres" => "NAYLETH ALBERTINA",
				"apellidos" => "RONDÓN RUEDA",
				"nacionalidad" => "V",
				"fechan" => "1974-01-11",
				"sexo" => "FEMENINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 17837726,
				"nombres" => "ENRIQUE ANTONIO",
				"apellidos" => "INFANTE LOPEZ",
				"nacionalidad" => "V",
				"fechan" => "1985-03-14",
				"sexo" => "MASCULINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 17999972,
				"nombres" => "VENECIA DE LOS ANGELES",
				"apellidos" => "RODRIGUEZ MARIN",
				"nacionalidad" => "V",
				"fechan" => "1985-12-13",
				"sexo" => "FEMENINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 13262157,
				"nombres" => "OSCAR ALEXANDER",
				"apellidos" => "ARTIGAS TERAN",
				"nacionalidad" => "V",
				"fechan" => "1976-08-25",
				"sexo" => "MASCULINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 13546155,
				"nombres" => "LUIS JOSE ",
				"apellidos" => "QUIJADA FUENTES ",
				"nacionalidad" => "V",
				"fechan" => "2021-03-14",
				"sexo" => "MASCULINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 8465512,
				"nombres" => "ARCADIA JOSEFINA",
				"apellidos" => "TORRES OSORIO",
				"nacionalidad" => "V",
				"fechan" => "1961-12-24",
				"sexo" => "FEMENINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 11168829,
				"nombres" => "ANDRES SABINO",
				"apellidos" => "BAYOLA MARIN",
				"nacionalidad" => "V",
				"fechan" => "1971-09-10",
				"sexo" => "MASCULINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 619277,
				"nombres" => "JULIO CESAR ",
				"apellidos" => "VASQUEZ",
				"nacionalidad" => "V",
				"fechan" => "1938-03-22",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 797662,
				"nombres" => "HIPOLITO RAFAEL",
				"apellidos" => "RODRIGUEZ DOMINGUEZ ",
				"nacionalidad" => "V",
				"fechan" => "1942-08-23",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 8874920,
				"nombres" => "JOSE GREGORIO",
				"apellidos" => "MERIDA FARIAS",
				"nacionalidad" => "V",
				"fechan" => "1963-10-09",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 8885476,
				"nombres" => "LUISA DEL ROSARIO",
				"apellidos" => "LOPEZ CARVAJAL ",
				"nacionalidad" => "V",
				"fechan" => "1967-05-17",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 9425480,
				"nombres" => "WILLIAM ALKAID",
				"apellidos" => "BOGGIO MARCANO",
				"nacionalidad" => "V",
				"fechan" => "1968-08-20",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 9896983,
				"nombres" => "LUIS ÁNGEL",
				"apellidos" => "CARRERA FIGUEROA ",
				"nacionalidad" => "V",
				"fechan" => "1966-04-25",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 10572077,
				"nombres" => "ANA ISABEL",
				"apellidos" => "APONTE CARIAS ",
				"nacionalidad" => "V",
				"fechan" => "1969-05-26",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 11169431,
				"nombres" => "JOSÉ LUIS",
				"apellidos" => "QUIJADA FUENTES ",
				"nacionalidad" => "V",
				"fechan" => "1972-05-04",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 11171955,
				"nombres" => "LUCYBEL",
				"apellidos" => "SOTILLO VALOR ",
				"nacionalidad" => "V",
				"fechan" => "1973-05-13",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 11173851,
				"nombres" => "JESÚS ARMANDO",
				"apellidos" => "MEDINA DRAEGERT ",
				"nacionalidad" => "V",
				"fechan" => "1972-10-07",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 11175805,
				"nombres" => "CLEVER JESÚS",
				"apellidos" => "TORRES RAMIREZ ",
				"nacionalidad" => "V",
				"fechan" => "1972-07-22",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 12185760,
				"nombres" => "ESMART JACKELINE",
				"apellidos" => "FARIAS",
				"nacionalidad" => "V",
				"fechan" => "1973-11-25",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 12185888,
				"nombres" => "CAROLA",
				"apellidos" => "SERRANO FLORES ",
				"nacionalidad" => "V",
				"fechan" => "1974-11-10",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 13015401,
				"nombres" => "YGMARY DE LOS ANGELES",
				"apellidos" => "CASTILLO ORTA ",
				"nacionalidad" => "V",
				"fechan" => "1977-09-10",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 13016985,
				"nombres" => "JEALITZA MARIA",
				"apellidos" => "ROUX FIGUERA ",
				"nacionalidad" => "V",
				"fechan" => "1975-10-16",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 13156099,
				"nombres" => "ALEXIS GREGORIO",
				"apellidos" => "VILLASANA",
				"nacionalidad" => "V",
				"fechan" => "1978-02-28",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 13326184,
				"nombres" => "ROSANA MARGARITA",
				"apellidos" => "PÉREZ DIAZ ",
				"nacionalidad" => "V",
				"fechan" => "1978-09-03",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 13452995,
				"nombres" => "ANGELA DINORAH",
				"apellidos" => "ESCALANTE MALAVE ",
				"nacionalidad" => "V",
				"fechan" => "1976-09-21",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 13507539,
				"nombres" => "EDUARDO JOSE",
				"apellidos" => "FLORES PARRA",
				"nacionalidad" => "V",
				"fechan" => "1977-08-04",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 13798699,
				"nombres" => "AINOSKY JAILEDIS",
				"apellidos" => "AREVALO TOVAR",
				"nacionalidad" => "V",
				"fechan" => "1963-10-09",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 14669998,
				"nombres" => "JOCXI KARINA",
				"apellidos" => "PRIETO GUZMAN ",
				"nacionalidad" => "V",
				"fechan" => "1979-03-07",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 16499444,
				"nombres" => "MARCO JOSUEE",
				"apellidos" => "GONZALEZ SANTA MARIA ",
				"nacionalidad" => "V",
				"fechan" => "1982-08-12",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 18014562,
				"nombres" => "MARIO JOSE",
				"apellidos" => "BRAVO GUTIERREZ ",
				"nacionalidad" => "V",
				"fechan" => "1988-11-11",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 22804159,
				"nombres" => "MARCO JOSE DE DIOS",
				"apellidos" => "ROMERO",
				"nacionalidad" => "V",
				"fechan" => "1993-12-31",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 23732346,
				"nombres" => "ROBERT ALEJANDRO",
				"apellidos" => "FILGUEIRA CASTILLO ",
				"nacionalidad" => "V",
				"fechan" => "1993-07-19",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 14516597,
				"nombres" => "ZORALYS ANDREINA",
				"apellidos" => "CHAVERO PACHECO",
				"nacionalidad" => "V",
				"fechan" => "1980-11-21",
				"sexo" => "FEMENINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 14517707,
				"nombres" => "WILLINOR JOSÉ",
				"apellidos" => "BASANTA MILLAN",
				"nacionalidad" => "V",
				"fechan" => "1979-06-07",
				"sexo" => "MASCULINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 14289241,
				"nombres" => "HERQUIS ARGOS",
				"apellidos" => "BARDINI ALI",
				"nacionalidad" => "V",
				"fechan" => "1980-06-24",
				"sexo" => "MASCULINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 12185954,
				"nombres" => "ALBERT DE JESUS",
				"apellidos" => "BRICEÑO MORA",
				"nacionalidad" => "V",
				"fechan" => "1975-07-18",
				"sexo" => "MASCULINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 11832298,
				"nombres" => "EDGAR JOSE",
				"apellidos" => "LEON MARCANO",
				"nacionalidad" => "V",
				"fechan" => "1973-05-20",
				"sexo" => "MASCULINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 8850664,
				"nombres" => "MARIA SOLEDAD",
				"apellidos" => "SAMPOL REYES",
				"nacionalidad" => "V",
				"fechan" => "1951-07-18",
				"sexo" => "FEMENINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 11174533,
				"nombres" => "RAQUEL MERCEDES",
				"apellidos" => "GONZALEZ DE RAMIREZ",
				"nacionalidad" => "V",
				"fechan" => "1972-07-09",
				"sexo" => "FEMENINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 12598129,
				"nombres" => "OLIANNE DEL VALLE",
				"apellidos" => "ZURITA LARA",
				"nacionalidad" => "V",
				"fechan" => "1975-04-13",
				"sexo" => "FEMENINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 15970936,
				"nombres" => "EBERTH ALBERTO",
				"apellidos" => "CARDOZO ROA",
				"nacionalidad" => "V",
				"fechan" => "1983-02-27",
				"sexo" => "MASCULINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 11226408,
				"nombres" => "GABRIELA BETZABE",
				"apellidos" => "MURILLO GRANADO ",
				"nacionalidad" => "V",
				"fechan" => "1972-04-11",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 11176979,
				"nombres" => "RAUL FELIPE",
				"apellidos" => "CABRERA PINEDA",
				"nacionalidad" => "V",
				"fechan" => "1971-11-05",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 13798198,
				"nombres" => "ROXANA CAROLINA",
				"apellidos" => "MAITA BASTARDO ",
				"nacionalidad" => "V",
				"fechan" => "1977-08-20",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 15468972,
				"nombres" => "JORBELIS ADRIANA",
				"apellidos" => "BERMUDEZ AQUINO ",
				"nacionalidad" => "V",
				"fechan" => "1982-02-12",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 16221530,
				"nombres" => "ANA DE DIOS",
				"apellidos" => "TUNAROZA MARTINEZ ",
				"nacionalidad" => "V",
				"fechan" => "1982-09-12",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 19369328,
				"nombres" => "EUCARIS DE LOS ANGELES",
				"apellidos" => "RIVAS RAMIREZ",
				"nacionalidad" => "V",
				"fechan" => "1989-03-24",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 15970578,
				"nombres" => "YASIL CAROLINA",
				"apellidos" => "ASCANIO RODRIGUEZ",
				"nacionalidad" => "V",
				"fechan" => "1983-10-13",
				"sexo" => "FEMENINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 8876147,
				"nombres" => "REINA",
				"apellidos" => "PARRA PEÑA ",
				"nacionalidad" => "V",
				"fechan" => "1964-01-06",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 4598383,
				"nombres" => "BERNARDO BAUDILIO",
				"apellidos" => "HERNÁNDEZ MUÑOZ",
				"nacionalidad" => "V",
				"fechan" => "1952-05-20",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 4983956,
				"nombres" => "CARMEN LUISA",
				"apellidos" => "DIAZ CARDOZO ",
				"nacionalidad" => "V",
				"fechan" => "1956-11-19",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 8894937,
				"nombres" => "DUWLIAN ANTONIO",
				"apellidos" => "MONTALTI ORTA ",
				"nacionalidad" => "V",
				"fechan" => "1969-04-17",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 8899699,
				"nombres" => "THAIZ ALICIA",
				"apellidos" => "LUGO GARCIA ",
				"nacionalidad" => "V",
				"fechan" => "1967-07-07",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 8899869,
				"nombres" => "LUISA ISABEL",
				"apellidos" => "GOMEZ LUNA ",
				"nacionalidad" => "V",
				"fechan" => "1968-11-19",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 8921875,
				"nombres" => "MARCO TULIO",
				"apellidos" => "ROMERO GONZALEZ ",
				"nacionalidad" => "V",
				"fechan" => "1966-12-24",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 9946992,
				"nombres" => "SONIA",
				"apellidos" => "ÁLVAREZ",
				"nacionalidad" => "V",
				"fechan" => "1967-07-20",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 10040636,
				"nombres" => "YOMELY JOSEFINA",
				"apellidos" => "PEREZ FAJARDO ",
				"nacionalidad" => "V",
				"fechan" => "1968-05-30",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 10049686,
				"nombres" => "JOSE LUIS",
				"apellidos" => " JIMENEZ HERRERA",
				"nacionalidad" => "V",
				"fechan" => "1971-01-18",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 10658254,
				"nombres" => "HECTOR ALFREDO",
				"apellidos" => "NAVAS ",
				"nacionalidad" => "V",
				"fechan" => "1971-02-25",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 10719405,
				"nombres" => "HECTOR JOSE",
				"apellidos" => "MOLINA NAVA",
				"nacionalidad" => "V",
				"fechan" => "1972-07-03",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 11168848,
				"nombres" => "ULISES ANTONIO",
				"apellidos" => "CASTRO GALEA ",
				"nacionalidad" => "V",
				"fechan" => "1972-02-13",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 11175485,
				"nombres" => "YESIKA ",
				"apellidos" => "RODRÍGUEZ",
				"nacionalidad" => "V",
				"fechan" => "2020-05-15",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 11289585,
				"nombres" => "ÁNGEL",
				"apellidos" => "MORALES",
				"nacionalidad" => "V",
				"fechan" => "1971-10-02",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 11723223,
				"nombres" => "LUIS ANTONIO",
				"apellidos" => "BRICEÑO ",
				"nacionalidad" => "V",
				"fechan" => "1972-11-08",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 12186666,
				"nombres" => "QUIRAR DEL CARMEN",
				"apellidos" => "AFANADOR QUIRPA",
				"nacionalidad" => "V",
				"fechan" => "1974-11-06",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 13016700,
				"nombres" => "YSLENIS CAROLINA",
				"apellidos" => "AWAD DIAZ ",
				"nacionalidad" => "V",
				"fechan" => "1978-04-23",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 13798088,
				"nombres" => "HERMES RODOLFO",
				"apellidos" => "MARCANO HERNANDEZ",
				"nacionalidad" => "V",
				"fechan" => "1975-06-14",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 13919383,
				"nombres" => "JOEL RAMON",
				"apellidos" => "POYO MANAURE ",
				"nacionalidad" => "V",
				"fechan" => "1981-11-11",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 15252062,
				"nombres" => "LUIS RAFAEL",
				"apellidos" => "BASTARDO  FARFAN ",
				"nacionalidad" => "V",
				"fechan" => "1981-11-02",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 15972550,
				"nombres" => "VIRGINIA DE LOS ÁNGELES",
				"apellidos" => "PARRA GARCÍA",
				"nacionalidad" => "V",
				"fechan" => "2021-03-14",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 16221079,
				"nombres" => "NIDIA FERNANDA",
				"apellidos" => "MACHADO CAMACHO",
				"nacionalidad" => "V",
				"fechan" => "1968-11-19",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 16499674,
				"nombres" => "FRAIDY MARIA",
				"apellidos" => "MORILLO MIRANDA",
				"nacionalidad" => "V",
				"fechan" => "1984-04-28",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 18076009,
				"nombres" => "JERAL STEVEN",
				"apellidos" => "GUAREZ NAVARRO",
				"nacionalidad" => "V",
				"fechan" => "2021-03-14",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 18335252,
				"nombres" => "LUZMEIDY DEL CARMEN",
				"apellidos" => "BRAVO MARRON ",
				"nacionalidad" => "V",
				"fechan" => "1986-11-20",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 19297990,
				"nombres" => "DIOSKARY JOSEFINA",
				"apellidos" => "MONRROY BERMUDEZ",
				"nacionalidad" => "V",
				"fechan" => "1981-11-02",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 19534827,
				"nombres" => "MARIAN DE LOS ÁNGELES",
				"apellidos" => "ADAMS JARAMILLO",
				"nacionalidad" => "V",
				"fechan" => "2021-03-14",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 20262051,
				"nombres" => "JESÚS RAFAEL",
				"apellidos" => "RAMOS STEPHENS",
				"nacionalidad" => "V",
				"fechan" => "2021-03-14",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 21264962,
				"nombres" => "DULCE MARÍA",
				"apellidos" => "PÉREZ SUÁREZ",
				"nacionalidad" => "V",
				"fechan" => "1992-09-12",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 24377317,
				"nombres" => "RAMÓN",
				"apellidos" => "MAITA",
				"nacionalidad" => "V",
				"fechan" => "1995-09-06",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 25036072,
				"nombres" => "DANIELA STEFANI",
				"apellidos" => "HERNANDEZ SALAZAR ",
				"nacionalidad" => "V",
				"fechan" => "1994-02-04",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 17047042,
				"nombres" => "DEY RENZO",
				"apellidos" => "RODRIGUEZ HERMAN",
				"nacionalidad" => "V",
				"fechan" => "1983-09-17",
				"sexo" => "MASCULINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 11173278,
				"nombres" => "RICHARD ALEJANDRO",
				"apellidos" => "MARTINEZ CARRASQUEL",
				"nacionalidad" => "V",
				"fechan" => "1972-07-12",
				"sexo" => "MASCULINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 24193923,
				"nombres" => "JACIEL JESUS",
				"apellidos" => "ALCALA",
				"nacionalidad" => "V",
				"fechan" => "1992-01-10",
				"sexo" => "MASCULINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 17162504,
				"nombres" => "OSMAR LENIN",
				"apellidos" => "GONZALEZ ESCORCHE",
				"nacionalidad" => "V",
				"fechan" => "1983-07-25",
				"sexo" => "MASCULINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 20079446,
				"nombres" => "JESUS ALBERTO",
				"apellidos" => "CEBALLOS PEREZ",
				"nacionalidad" => "V",
				"fechan" => "1987-02-20",
				"sexo" => "MASCULINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 14409362,
				"nombres" => "NUÑEZ",
				"apellidos" => "JORGE JOSÉ",
				"nacionalidad" => "V",
				"fechan" => "1974-12-15",
				"sexo" => "MASCULINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 10045919,
				"nombres" => "JESUS RAMON",
				"apellidos" => "VALDEZ RAMOS",
				"nacionalidad" => "V",
				"fechan" => "1968-07-06",
				"sexo" => "MASCULINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 8872125,
				"nombres" => "YAMILET VICENTA",
				"apellidos" => "MIRANDA LOPEZ",
				"nacionalidad" => "V",
				"fechan" => "1963-12-14",
				"sexo" => "FEMENINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 8887535,
				"nombres" => "MARIA CELESTE",
				"apellidos" => "AGUIRRE PEREZ",
				"nacionalidad" => "V",
				"fechan" => "1965-07-20",
				"sexo" => "FEMENINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 10047956,
				"nombres" => "KAREN JOSEFINA",
				"apellidos" => "RANGEL MARTINEZ",
				"nacionalidad" => "V",
				"fechan" => "1969-07-01",
				"sexo" => "FEMENINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 14286048,
				"nombres" => "CARMEN BEATRIZ",
				"apellidos" => "CARMONA PUENTE",
				"nacionalidad" => "V",
				"fechan" => "1980-12-10",
				"sexo" => "FEMENINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 10565005,
				"nombres" => "PEDRO OSWALDO",
				"apellidos" => "APARICIO BASANTA",
				"nacionalidad" => "V",
				"fechan" => "2021-03-14",
				"sexo" => "MASCULINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 15352693,
				"nombres" => "YOSWARD ALEXANDER",
				"apellidos" => "NARVAEZ GIL",
				"nacionalidad" => "V",
				"fechan" => "2021-03-14",
				"sexo" => "MASCULINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 19060789,
				"nombres" => "LOURDES NATALIE",
				"apellidos" => "RONDON COLMENARES",
				"nacionalidad" => "V",
				"fechan" => "1990-03-27",
				"sexo" => "FEMENINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 4597581,
				"nombres" => "LINO",
				"apellidos" => "VERA",
				"nacionalidad" => "V",
				"fechan" => "1954-11-04",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 8875726,
				"nombres" => "HERMOGENES JÓSE",
				"apellidos" => "PÉREZ BRITO ",
				"nacionalidad" => "V",
				"fechan" => "1961-09-02",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 11173641,
				"nombres" => "WILLFOR RAFAEL",
				"apellidos" => "GOUDETH GALINDO",
				"nacionalidad" => "V",
				"fechan" => "1972-05-15",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 12193940,
				"nombres" => "YONNY ANTONIO",
				"apellidos" => "BRITO SANZONETTI ",
				"nacionalidad" => "V",
				"fechan" => "1976-09-15",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 3777956,
				"nombres" => "JOSÉ RAMON",
				"apellidos" => "DIAZ MENDEZ ",
				"nacionalidad" => "V",
				"fechan" => "1951-05-04",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 7223492,
				"nombres" => "DOMINGO ISIDRO",
				"apellidos" => "BASTARRICA SIMANCAS ",
				"nacionalidad" => "V",
				"fechan" => "1963-10-13",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 8918233,
				"nombres" => "EDGAR MIGUEL",
				"apellidos" => "ORFILA INFANTE",
				"nacionalidad" => "V",
				"fechan" => "1965-02-21",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 10044937,
				"nombres" => "CARLOS ALBERTO",
				"apellidos" => "HERNANDEZ RIVAS ",
				"nacionalidad" => "V",
				"fechan" => "2007-03-20",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 10570624,
				"nombres" => "CARLOS ALBERTO",
				"apellidos" => "GÍL MÁRQUEZ ",
				"nacionalidad" => "V",
				"fechan" => "2004-03-08",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 11169702,
				"nombres" => "JHONNY ALEXANDER",
				"apellidos" => "GUTIERREZ MORILLO ",
				"nacionalidad" => "V",
				"fechan" => "1971-04-16",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 11723378,
				"nombres" => "ARLEN JOSEFINA",
				"apellidos" => "GARCIA VILLAROEL ",
				"nacionalidad" => "V",
				"fechan" => "1974-01-19",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 11727526,
				"nombres" => "MARYORY",
				"apellidos" => "MENDOZA HERNANDEZ ",
				"nacionalidad" => "V",
				"fechan" => "1974-12-11",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 12188759,
				"nombres" => "EUCARIS DEL VALLE",
				"apellidos" => "AVILA ",
				"nacionalidad" => "V",
				"fechan" => "1973-07-09",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 12192184,
				"nombres" => "RAIDA",
				"apellidos" => "RAMOS",
				"nacionalidad" => "V",
				"fechan" => "1990-12-23",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 13015414,
				"nombres" => "JORGE JOSE",
				"apellidos" => "ROJAS CEDEÑO ",
				"nacionalidad" => "V",
				"fechan" => "1975-06-27",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 13016768,
				"nombres" => "KATERINE GIOVE",
				"apellidos" => "MARCHAN HERNADEZ ",
				"nacionalidad" => "V",
				"fechan" => "1976-08-28",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 13244869,
				"nombres" => "NEURO RAMON",
				"apellidos" => "SOLUTA MATOS",
				"nacionalidad" => "V",
				"fechan" => "1975-04-05",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 14144336,
				"nombres" => "OSMILE ELINOR ",
				"apellidos" => "DURAN CEDEÑO ",
				"nacionalidad" => "V",
				"fechan" => "1979-05-14",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 14289496,
				"nombres" => "YESIKA DEL CARMEN",
				"apellidos" => "PEREZ SILVA ",
				"nacionalidad" => "V",
				"fechan" => "1978-09-25",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 14410694,
				"nombres" => "ANDRES RAFAEL",
				"apellidos" => "MARTINEZ TARRIO ",
				"nacionalidad" => "V",
				"fechan" => "1981-05-05",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 15125989,
				"nombres" => "ARMANDO ALFONZO",
				"apellidos" => "ALVAREZ MORALES ",
				"nacionalidad" => "V",
				"fechan" => "1980-08-04",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 15251859,
				"nombres" => "HERMES DANIEL",
				"apellidos" => "SUAREZ FIGUEREDO ",
				"nacionalidad" => "V",
				"fechan" => "1981-12-07",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 15636457,
				"nombres" => "MILEIDIS DEL VALLE",
				"apellidos" => "MUÑOZ PINO ",
				"nacionalidad" => "V",
				"fechan" => "1982-06-03",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 15636866,
				"nombres" => "GREGORIO VICENTE",
				"apellidos" => "GUZMAN MAUCO ",
				"nacionalidad" => "V",
				"fechan" => "1983-11-17",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 15638343,
				"nombres" => "JOSE GREGORIO",
				"apellidos" => "MARIN FUENTES ",
				"nacionalidad" => "V",
				"fechan" => "1982-06-16",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 16034415,
				"nombres" => "JULIANA ROSSABETH",
				"apellidos" => "GALINDEZ COA ",
				"nacionalidad" => "V",
				"fechan" => "1981-08-29",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 16759927,
				"nombres" => "PEDRO YOEL NICANOR",
				"apellidos" => "CALDERA BACA ",
				"nacionalidad" => "V",
				"fechan" => "1984-08-26",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 17047916,
				"nombres" => "VICTOR MANUEL",
				"apellidos" => "STANFORD GAMBOA ",
				"nacionalidad" => "V",
				"fechan" => "1985-03-08",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 18012307,
				"nombres" => "ROSIRIS DEL CARMEN",
				"apellidos" => "MENDOZA RAMIREZ",
				"nacionalidad" => "V",
				"fechan" => "1985-08-24",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 18476572,
				"nombres" => "ELISQUEIDIS JOSEFINA",
				"apellidos" => "SARMIENTO OCHOA ",
				"nacionalidad" => "V",
				"fechan" => "1988-10-25",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 19475396,
				"nombres" => "ISAIAS DE JESUS",
				"apellidos" => "GONZALEZ GONZALEZ",
				"nacionalidad" => "V",
				"fechan" => "1987-07-06",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 23552404,
				"nombres" => "ARLET DEMARIA",
				"apellidos" => "FERNANDEZ CANO ",
				"nacionalidad" => "V",
				"fechan" => "1983-04-17",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 17046077,
				"nombres" => "NORMALIS ISABEL",
				"apellidos" => "HERNANDEZ ANGULO",
				"nacionalidad" => "V",
				"fechan" => "1985-08-22",
				"sexo" => "FEMENINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 15619147,
				"nombres" => "GABRIEL ENRIQUE",
				"apellidos" => "MATOS ALCALÁ",
				"nacionalidad" => "V",
				"fechan" => "1981-03-13",
				"sexo" => "MASCULINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 13658685,
				"nombres" => "ROSELA ASTRID",
				"apellidos" => "LOZANO NEIRA",
				"nacionalidad" => "V",
				"fechan" => "1978-08-17",
				"sexo" => "FEMENINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 13798763,
				"nombres" => "MARUSKA",
				"apellidos" => "RODRIGUEZ NEVI",
				"nacionalidad" => "V",
				"fechan" => "1977-10-14",
				"sexo" => "FEMENINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 13336668,
				"nombres" => "CAROLINA MILAGROS",
				"apellidos" => "OTERO RODRIGUEZ",
				"nacionalidad" => "V",
				"fechan" => "1978-03-25",
				"sexo" => "FEMENINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 13348095,
				"nombres" => "ANGEL ADRIAN",
				"apellidos" => "GARCÍA",
				"nacionalidad" => "V",
				"fechan" => "1977-09-19",
				"sexo" => "MASCULINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 13452041,
				"nombres" => "MARIELBA",
				"apellidos" => "RODRIGUEZ BRICEÑO",
				"nacionalidad" => "V",
				"fechan" => "1976-05-11",
				"sexo" => "MASCULINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 12644073,
				"nombres" => "MARIA LUISA",
				"apellidos" => "GONZALEZ GUTIERREZ",
				"nacionalidad" => "V",
				"fechan" => "1975-10-25",
				"sexo" => "FEMENINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 12814050,
				"nombres" => "YORLEY MARELY",
				"apellidos" => "CASANOVA MORA",
				"nacionalidad" => "V",
				"fechan" => "1976-04-05",
				"sexo" => "FEMENINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 11731348,
				"nombres" => "KATIUSKA DEL CARMEN",
				"apellidos" => "CHAPARRO DE MONTAÑEZ",
				"nacionalidad" => "V",
				"fechan" => "1975-02-18",
				"sexo" => "FEMENINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 17138869,
				"nombres" => "HIMBERT RAFAEL",
				"apellidos" => "PERDOMO FIGUEREDO",
				"nacionalidad" => "V",
				"fechan" => "1984-11-05",
				"sexo" => "MASCULINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 17837238,
				"nombres" => "ISAAC ALFONSO",
				"apellidos" => "QUINTERO CARIAS",
				"nacionalidad" => "V",
				"fechan" => "1986-05-30",
				"sexo" => "MASCULINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 16222227,
				"nombres" => "JONAS GREGORIO",
				"apellidos" => "VILLASANA PEREZ",
				"nacionalidad" => "V",
				"fechan" => "1984-03-30",
				"sexo" => "MASCULINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 19078025,
				"nombres" => "EDGAR ALEJANDRO",
				"apellidos" => "ALCALA GARCIA",
				"nacionalidad" => "V",
				"fechan" => "1987-04-15",
				"sexo" => "MASCULINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 15972925,
				"nombres" => "KARINA",
				"apellidos" => "PEÑA",
				"nacionalidad" => "V",
				"fechan" => "2021-03-14",
				"sexo" => "FEMENINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 13920077,
				"nombres" => "MARIA",
				"apellidos" => "HERNANDEZ",
				"nacionalidad" => "V",
				"fechan" => "1979-12-21",
				"sexo" => "FEMENINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 14402269,
				"nombres" => "MARVIN CAROLINA",
				"apellidos" => "ROBLES ORTIZ",
				"nacionalidad" => "V",
				"fechan" => "1978-09-03",
				"sexo" => "FEMENINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 10573756,
				"nombres" => "LUIS JOSÉ",
				"apellidos" => "GRANADO SANCHEZ",
				"nacionalidad" => "V",
				"fechan" => "1970-11-15",
				"sexo" => "MASCULINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 14986577,
				"nombres" => "MAIVELLY JOSEFINA",
				"apellidos" => "BOLIVAR GUTIERREZ",
				"nacionalidad" => "V",
				"fechan" => "1980-03-17",
				"sexo" => "FEMENINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 3900856,
				"nombres" => "MEBER CRISTINA",
				"apellidos" => "DASILVA MARTINEZ",
				"nacionalidad" => "V",
				"fechan" => "1956-05-08",
				"sexo" => "FEMENINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 12270370,
				"nombres" => "OLY YURUMA",
				"apellidos" => "RODRIGUEZ MATTEY",
				"nacionalidad" => "V",
				"fechan" => "1975-07-02",
				"sexo" => "FEMENINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 3851202,
				"nombres" => "FRANCIS YOLANDA",
				"apellidos" => "TINEO LIMPIO",
				"nacionalidad" => "V",
				"fechan" => "1955-04-16",
				"sexo" => "FEMENINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 10934419,
				"nombres" => "JAMES EDWARD",
				"apellidos" => "MASSIAH MATUTE",
				"nacionalidad" => "V",
				"fechan" => "1973-05-11",
				"sexo" => "MASCULINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 8860493,
				"nombres" => "IRASEMA ISABEL",
				"apellidos" => "CARABALLO RODRÍGUEZ",
				"nacionalidad" => "V",
				"fechan" => "1962-07-31",
				"sexo" => "FEMENINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 592434,
				"nombres" => "ROBERTO BERALMINO",
				"apellidos" => "YEGUEZ MARCANO",
				"nacionalidad" => "V",
				"fechan" => "1941-05-13",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 3760543,
				"nombres" => "ORLANDO DEL CARMEN",
				"apellidos" => "AMARISTA BETANCOURT",
				"nacionalidad" => "V",
				"fechan" => "1952-04-18",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 5457080,
				"nombres" => "RAFAEL ANTONIO",
				"apellidos" => "MORENO DIAZ",
				"nacionalidad" => "V",
				"fechan" => "1969-09-17",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 5556006,
				"nombres" => "MERCEDES DEL ROSARIO",
				"apellidos" => "ALCALA MARTINEZ ",
				"nacionalidad" => "V",
				"fechan" => "1960-04-05",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 7912502,
				"nombres" => "GUSTAVO JOSÉ",
				"apellidos" => "MARTURET PÉREZ ",
				"nacionalidad" => "V",
				"fechan" => "1967-09-07",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 8850360,
				"nombres" => "RAMON ANTONIO",
				"apellidos" => "FLORES RODRIGUEZ ",
				"nacionalidad" => "V",
				"fechan" => "1958-10-31",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 8872046,
				"nombres" => "MINO",
				"apellidos" => "URBANI BRITO ",
				"nacionalidad" => "V",
				"fechan" => "1962-11-24",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 8894115,
				"nombres" => "ROGER JOSÉ",
				"apellidos" => "MEDINA OLIVO ",
				"nacionalidad" => "V",
				"fechan" => "1967-06-19",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 8982698,
				"nombres" => "MAGSIEL JOSE",
				"apellidos" => "SALAZAR BELISARIO",
				"nacionalidad" => "V",
				"fechan" => "1969-09-17",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 10569901,
				"nombres" => "JOSÉ GREGORIO",
				"apellidos" => "MEJIAS TORRES",
				"nacionalidad" => "V",
				"fechan" => "1970-10-03",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 10932039,
				"nombres" => "SAÚL ANTONIO",
				"apellidos" => "RAMOS GARCÍA ",
				"nacionalidad" => "V",
				"fechan" => "1970-09-15",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 11171563,
				"nombres" => "JOSE ANGEL",
				"apellidos" => "LEE BRAVO ",
				"nacionalidad" => "V",
				"fechan" => "1972-10-28",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 11393453,
				"nombres" => "YAJAIRA CAROLINA",
				"apellidos" => "MARQUEZ DE SANABRIA ",
				"nacionalidad" => "V",
				"fechan" => "1974-07-23",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 11732377,
				"nombres" => "PEDRO ALEXANDER",
				"apellidos" => "REINA GONZALEZ ",
				"nacionalidad" => "V",
				"fechan" => "1969-09-25",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 12187444,
				"nombres" => "CARLOS EDUARDO",
				"apellidos" => "TOLEDO ROMERO ",
				"nacionalidad" => "V",
				"fechan" => "1976-02-05",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 13015992,
				"nombres" => "JOAN ANTONIO",
				"apellidos" => "BARRETO CORREA ",
				"nacionalidad" => "V",
				"fechan" => "1978-05-11",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 13595022,
				"nombres" => "LUIS ALFONZO",
				"apellidos" => "BARRIOS MORÓN",
				"nacionalidad" => "V",
				"fechan" => "1977-06-13",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 14054813,
				"nombres" => "KENNY ALEJANDRO",
				"apellidos" => "URIEPERO HERNÁNDEZ",
				"nacionalidad" => "V",
				"fechan" => "1968-12-06",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 14516952,
				"nombres" => "MARIA ANGELICA",
				"apellidos" => "BERVIS SAAVEDRA ",
				"nacionalidad" => "V",
				"fechan" => "1979-11-23",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 14516970,
				"nombres" => "YIRSIA RAQUEL",
				"apellidos" => "MARTINEZ GONZALEZ ",
				"nacionalidad" => "V",
				"fechan" => "1980-11-11",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 14669625,
				"nombres" => "ELIEBER ANTONIO",
				"apellidos" => "GUEVARA",
				"nacionalidad" => "V",
				"fechan" => "1997-02-17",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 15637061,
				"nombres" => "ROIMELIZ JOSE",
				"apellidos" => "ZAMBRANO LOPEZ ",
				"nacionalidad" => "V",
				"fechan" => "1982-02-22",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 15970419,
				"nombres" => "OSKARINA DEL VALLE",
				"apellidos" => "BOLIVAR GAMEZ ",
				"nacionalidad" => "V",
				"fechan" => "1984-03-12",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 16219784,
				"nombres" => "TRINO JOSE",
				"apellidos" => "SOLORZANO MALPICA",
				"nacionalidad" => "V",
				"fechan" => "1983-04-07",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 16499093,
				"nombres" => "EDGLYS ROSA",
				"apellidos" => "PRADO LANDAETA ",
				"nacionalidad" => "V",
				"fechan" => "1983-10-14",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 16757101,
				"nombres" => "JAMAICA",
				"apellidos" => "FERNÁNDEZ",
				"nacionalidad" => "V",
				"fechan" => "1983-08-09",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 17045627,
				"nombres" => "DAYANA MERCEDES A. ",
				"apellidos" => "MÉNDEZ ALVAREZ ",
				"nacionalidad" => "V",
				"fechan" => "1985-02-14",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 17839380,
				"nombres" => "JOSER JOSE",
				"apellidos" => "MENDEZ ARZOLA ",
				"nacionalidad" => "V",
				"fechan" => "1987-05-03",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 24796954,
				"nombres" => "KAYSERI YEBRAXI",
				"apellidos" => "TORREALBA FEMAYOR",
				"nacionalidad" => "V",
				"fechan" => "1996-03-20",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 25685096,
				"nombres" => "JULIO CESAR",
				"apellidos" => "TOLEDO MARTINEZ",
				"nacionalidad" => "V",
				"fechan" => "1997-02-17",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 26139640,
				"nombres" => "KEVIN GABRIEL",
				"apellidos" => "SALAZAR",
				"nacionalidad" => "V",
				"fechan" => "1981-11-20",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 15469516,
				"nombres" => "LYNN RAFAEL",
				"apellidos" => "HERNANDEZ ROJAS",
				"nacionalidad" => "V",
				"fechan" => "1983-02-26",
				"sexo" => "MASCULINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 14518485,
				"nombres" => "ROIMER JOSE",
				"apellidos" => "ZAMBRANO LOPEZ",
				"nacionalidad" => "V",
				"fechan" => "1981-04-05",
				"sexo" => "MASCULINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 13156511,
				"nombres" => "JUAN CARLOS",
				"apellidos" => "OROPEZA MATOS",
				"nacionalidad" => "V",
				"fechan" => "1976-07-10",
				"sexo" => "MASCULINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 12359973,
				"nombres" => "CRISTHIAN KARINA",
				"apellidos" => "ORTEGA",
				"nacionalidad" => "V",
				"fechan" => "1975-03-19",
				"sexo" => "FEMENINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 11174797,
				"nombres" => "RAIZA",
				"apellidos" => "CASTILLO CHACIN",
				"nacionalidad" => "V",
				"fechan" => "1970-10-03",
				"sexo" => "FEMENINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 5555270,
				"nombres" => "ARACELIS JOSEFINA",
				"apellidos" => "BARRIOS CORDOLIANI",
				"nacionalidad" => "V",
				"fechan" => "1961-02-12",
				"sexo" => "FEMENINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 8881297,
				"nombres" => "BENITO JOSÉ",
				"apellidos" => "QUIROZ ESTANGA",
				"nacionalidad" => "V",
				"fechan" => "1964-12-01",
				"sexo" => "MASCULINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 7214767,
				"nombres" => "JOSÉ ENRIQUE",
				"apellidos" => "MARTINEZ PÉREZ",
				"nacionalidad" => "V",
				"fechan" => "1962-08-19",
				"sexo" => "MASCULINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 4596850,
				"nombres" => "DINARCO ANTONIO",
				"apellidos" => "PULVETT GRILLET",
				"nacionalidad" => "V",
				"fechan" => "1956-06-18",
				"sexo" => "MASCULINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 4035318,
				"nombres" => "FEDOR ANTONIO",
				"apellidos" => "REYES TORREALBA",
				"nacionalidad" => "V",
				"fechan" => "1955-01-10",
				"sexo" => "MASCULINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 19536873,
				"nombres" => "MINO JOSE",
				"apellidos" => "URBANI DIAZ",
				"nacionalidad" => "V",
				"fechan" => "2021-03-14",
				"sexo" => "MASCULINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 4939849,
				"nombres" => "LEONOR MARIA",
				"apellidos" => "RUBIO TORRES",
				"nacionalidad" => "V",
				"fechan" => "2007-08-29",
				"sexo" => "MASCULINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 7210726,
				"nombres" => "KETTY DEL PINO",
				"apellidos" => "FEREGOTTO DE AVILEZ",
				"nacionalidad" => "V",
				"fechan" => "1961-07-13",
				"sexo" => "FEMENINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 10843310,
				"nombres" => "VICTOR MANUEL",
				"apellidos" => "PÉREZ PACHECO",
				"nacionalidad" => "V",
				"fechan" => "1972-09-19",
				"sexo" => "MASCULINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 15136468,
				"nombres" => "JOSE ANTONIO",
				"apellidos" => "SAAVEDRA ABARULLO",
				"nacionalidad" => "V",
				"fechan" => "1981-01-26",
				"sexo" => "MASCULINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 11172197,
				"nombres" => "ANA MARIA",
				"apellidos" => "VERA PATETE",
				"nacionalidad" => "V",
				"fechan" => "1970-08-09",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 11727959,
				"nombres" => "DILYS KARINA",
				"apellidos" => "VERA MARTINEAU ",
				"nacionalidad" => "V",
				"fechan" => "1974-03-09",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 12652251,
				"nombres" => "DAISY COROMOTO",
				"apellidos" => "DIAZ PIERO",
				"nacionalidad" => "V",
				"fechan" => "1997-02-17",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 13507455,
				"nombres" => "KARLA KARINA",
				"apellidos" => "YANEZ APONTE ",
				"nacionalidad" => "V",
				"fechan" => "1977-01-17",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 14223882,
				"nombres" => "ANA ALEJANDRA",
				"apellidos" => "BAISDEN GUERRA ",
				"nacionalidad" => "V",
				"fechan" => "1979-06-18",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 16025713,
				"nombres" => "SUNEIDYS JOSEFINA",
				"apellidos" => "OREA ARZOLA ",
				"nacionalidad" => "V",
				"fechan" => "1982-02-04",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 16944781,
				"nombres" => "YUSMERIS DEL VALLE",
				"apellidos" => "ROMERO IDROGO ",
				"nacionalidad" => "V",
				"fechan" => "1984-02-24",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 14402371,
				"nombres" => "CORONADO GRANADO",
				"apellidos" => "LUZMILA YAMILETH",
				"nacionalidad" => "V",
				"fechan" => "1980-01-24",
				"sexo" => "FEMENINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 6514076,
				"nombres" => "MARIO ALBERTO",
				"apellidos" => "RAMSAY HAYWOOD",
				"nacionalidad" => "V",
				"fechan" => "1969-09-27",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 8877605,
				"nombres" => "ANGEL REYES",
				"apellidos" => "VILLAFAÑA RODRÍGUEZ ",
				"nacionalidad" => "V",
				"fechan" => "1965-10-29",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 10047178,
				"nombres" => "OFELIA DE JESUS",
				"apellidos" => "CORNIELES CASTRO ",
				"nacionalidad" => "V",
				"fechan" => "1969-05-06",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 10565275,
				"nombres" => "RICHARD DAVID",
				"apellidos" => "OSORIO PINTO ",
				"nacionalidad" => "V",
				"fechan" => "1971-03-30",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 11728670,
				"nombres" => "NEPTALI JESUS",
				"apellidos" => "CASTILLEJOS MAESTRE ",
				"nacionalidad" => "V",
				"fechan" => "1975-06-14",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 12188595,
				"nombres" => "ULISES DEL VALLE",
				"apellidos" => "ROJAS GUEVARA",
				"nacionalidad" => "V",
				"fechan" => "1974-12-20",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 12601234,
				"nombres" => "CESAR DANIEL",
				"apellidos" => "GUZMAN MARQUEZ ",
				"nacionalidad" => "V",
				"fechan" => "1976-05-05",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 13327301,
				"nombres" => "DAYANNA JOSEFA",
				"apellidos" => "BOLIVAR SALAZAR ",
				"nacionalidad" => "V",
				"fechan" => "1978-09-13",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 13799472,
				"nombres" => "JOSE LUIS",
				"apellidos" => "CASTRO SOTO",
				"nacionalidad" => "V",
				"fechan" => "1978-12-13",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 15476598,
				"nombres" => "NEOMAR ANTONIO ",
				"apellidos" => "FERNANDEZ ",
				"nacionalidad" => "V",
				"fechan" => "1981-09-11",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 15637773,
				"nombres" => "JAIRO ELIESER",
				"apellidos" => "GARCÍA",
				"nacionalidad" => "V",
				"fechan" => "1981-09-19",
				"sexo" => "MASCULINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 16758685,
				"nombres" => "DOULEIDYS CAROLINA",
				"apellidos" => "ARIAS AQUINO",
				"nacionalidad" => "V",
				"fechan" => "1985-04-27",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 16914157,
				"nombres" => "NAIROBIS DEL VALLE",
				"apellidos" => "LOPEZ MARTINEZ ",
				"nacionalidad" => "V",
				"fechan" => "1983-04-04",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 18012369,
				"nombres" => "FRANCIS CAROLINA",
				"apellidos" => "AGREDA TAMICHE ",
				"nacionalidad" => "V",
				"fechan" => "1986-06-27",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 18623658,
				"nombres" => "MORELLYS DAYANAITH",
				"apellidos" => "LOZANO DORÉ ",
				"nacionalidad" => "V",
				"fechan" => "1987-10-12",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 20079062,
				"nombres" => "NELDYS DEL CARMEN",
				"apellidos" => "ORDOÑEZ LEON ",
				"nacionalidad" => "V",
				"fechan" => "1988-12-06",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 23733106,
				"nombres" => "ANGELA MARIA",
				"apellidos" => "FLOREZ BRITO",
				"nacionalidad" => "V",
				"fechan" => "1994-01-17",
				"sexo" => "FEMENINO",
				"estatus" => "ACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 15969072,
				"nombres" => "GARCIA TORRES",
				"apellidos" => "YASMILDRE ELOISA",
				"nacionalidad" => "V",
				"fechan" => "1981-06-06",
				"sexo" => "FEMENINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 14409780,
				"nombres" => "ALEXIS QUIJADA",
				"apellidos" => "ESTHER MARINA ",
				"nacionalidad" => "V",
				"fechan" => "1980-03-12",
				"sexo" => "FEMENINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 12599001,
				"nombres" => " YUSLEMIS MILAGROS",
				"apellidos" => "SUCRE",
				"nacionalidad" => "V",
				"fechan" => "2021-03-14",
				"sexo" => "FEMENINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
			array(
				"cedula" => 10574888,
				"nombres" => "MARGOT MATILDE",
				"apellidos" => "TORRES YEGRES",
				"nacionalidad" => "V",
				"fechan" => "1971-11-21",
				"sexo" => "FEMENINO",
				"estatus" => "INACTIVO",
				"created_at" => $now,
				"updated_at" => $now,
			),
		);

        Docente::insert([
			[
				'cedula' => 0 ,
				'nombres' => 'SIN' ,
				'apellidos' => 'ASIGNAR' ,
				'nacionalidad' => 'V' ,
				'sexo' => 'MASCULINO' ,
				'fechan' =>  '2021-01-01',
				'estatus' => 'ACTIVO',
				'created_at'=> $now,
				'updated_at'=> $now
			],
			[
				'cedula' => 1 ,
				'nombres' => 'AUXILIAR' ,
				'apellidos' => 'AUXILIAR' ,
				'nacionalidad' => 'V' ,
				'sexo' => 'MASCULINO' ,
				'fechan' =>  '2021-01-01',
				'estatus' => 'ACTIVO',
				'created_at'=> $now,
				'updated_at'=> $now
			]
			]
		);

		Docente::insert($docentes);
    }
}
